//! Universal Data Transfer Objects (DTOs) for Souls Engine (v7).
//!
//! Encompasses FinOps cost metrics ($E^3$), hardware telemetry (RTX 2060m/WDDM),
//! and swarm coordination models (sub_agent_diaries, context_ledger, handoff).

use serde::{Deserialize, Serialize};

// ============================================================================
// 1. FinOps, Routing & E³ Cost Structures
// ============================================================================

/// Model execution tier classification for the Zero-Trust cascade.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ModelTier {
    /// Nuvem de ponta (ex: Claude 3.5 Sonnet, DeepSeek V3) para tarefas reflexivas.
    PremiumCloud,
    /// Nuvem rápida e econômica (ex: Gemini Flash, Haiku) para triagem e síntese leve.
    FlashCloud,
    /// Silício local bare-metal (RTX 2060m / CPU Intel AVX2) com custo zero.
    LocalGPU,
}

/// Routing tier identifiers for the ParetoBandit decision engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RoutingTier {
    /// Nível 0: Local Velocista (LFM 1.2B / ONNX / ModernBERT). Custo $0.
    Tier0,
    /// Nível 1: Local Trator (Nemotron 4B / Qwen Coder na dGPU). Custo $0.
    Tier1,
    /// Nível 2: Nuvem Premium (DeepSeek / Claude). Custo por token.
    Tier2,
}

/// Routing determination generated by IronCostBreaker.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AllowedRoute {
    /// Rota original aprovada para o tier indicado.
    OriginalRoute(ModelTier),
    /// Orçamento esgotado mas payload suportado pela VRAM local: fallback gracioso.
    FallbackToLocal,
    /// Bloqueio total: orçamento excedido e payload incompatível com a VRAM.
    Blocked,
}

/// Multidimensional efficiency, economics, and execution metrics ($E^3$).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FinOpsCostMetrics {
    pub prefill_tokens: u64,
    pub generation_tokens: u64,
    pub total_tokens: u64,
    pub latency_ms: f64,
    pub cost_usd: f64,
    pub quality_score: Option<f32>,
    pub e3_score: f64,
    pub deviation_ratio: Option<f32>,
}

/// Normalized $E^3$ score breakdown.
///
/// Composites efficiency (latency/throughput), economics (cost per quality unit),
/// and execution (accuracy/compliance) into an aggregated utility score.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct E3EfficiencyScore {
    pub efficiency: f64,
    pub economics: f64,
    pub execution: f64,
    pub composite_score: f64,
}

impl E3EfficiencyScore {
    #[must_use]
    pub fn new(efficiency: f64, economics: f64, execution: f64) -> Self {
        // Weighted average: 40% execution, 35% economics, 25% efficiency
        let composite_score = (execution * 0.40) + (economics * 0.35) + (efficiency * 0.25);
        Self {
            efficiency,
            economics,
            execution,
            composite_score,
        }
    }
}

/// Candidate model for Pareto utility evaluation: U = q - (lambda * c) - (beta * l).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ModelCandidate {
    pub model_id: String,
    pub tier: ModelTier,
    /// Expected accuracy/quality (0.0..=1.0).
    pub expected_quality: f32,
    /// Cost in micro-USD per request.
    pub api_cost_micro_usd: f32,
    /// Estimated end-to-end latency in milliseconds.
    pub estimated_latency_ms: f32,
}

/// Batch record emitted to SQLite `telemetry_events` table (STRICT).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TelemetryBatchRecord {
    pub id: String,
    pub session_id: String,
    pub event_type: String,
    pub execution_tier: String,
    pub payload_json: String,
    pub latency_ms: f64,
    pub tokens_input: i64,
    pub tokens_output: i64,
    pub direct_cost_usd: f64,
    pub e3_score: f64,
    pub created_at: i64,
}

/// Epistemic partition governing memory retention policies (SCHEMAS_DDL_MANIFEST.md).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum EpistemicPartition {
    /// Permanent facts and architectural directives; immune to Langevin Decay.
    Stable,
    /// Conversational context subjected to metabolic half-life decay.
    Evolving,
}

/// Canonical record mapped from `epistemic_memories` table (STRICT).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EpistemicMemoryRecord {
    pub id: String,
    pub session_id: String,
    pub category: String,
    pub content: String,
    pub partition: EpistemicPartition,
    pub salience: f32,
    pub access_count: i64,
    pub source_ref: Option<String>,
    pub created_at: i64,
    pub last_accessed_at: i64,
    pub updated_at: i64,
}

// ============================================================================
// 2. Hardware Telemetry & Thermal Watchdog DTOs (RTX 2060m / WDDM)
// ============================================================================

/// Physical VRAM allocation ceiling for NVIDIA GeForce RTX 2060m (6,144 MB).
pub const RTX_2060M_VRAM_TOTAL_MB: u32 = 6_144;

/// Safe usable VRAM ceiling under Windows 11 Desktop Window Manager (~5,294 MB).
pub const RTX_2060M_WDDM_CEILING_MB: u32 = 5_294;

/// Minimum PCIe bus throughput required to sustain KV cache spillover without collapse (GB/s).
pub const MIN_PCIE_BANDWIDTH_GBPS_FOR_SPILLOVER: f32 = 32.0;

/// Snapshot of physical host and GPU resources collected by the NVML watchdog.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HardwareTelemetry {
    pub vram_used_mb: u32,
    pub vram_total_mb: u32,
    pub ram_used_mb: u32,
    pub ram_total_mb: u32,
    pub cpu_temp_celsius: f32,
    pub gpu_temp_celsius: f32,
    pub pcie_bandwidth_gbps: f32,
    pub thermal_throttle: bool,
    pub timestamp_epoch_ms: i64,
}

/// Snapshot of Peak Exponentially Weighted Moving Average (PeakEWMA) latency metrics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EwmaMetrics {
    pub alpha: f32,
    pub ewma_latency_ms: f64,
    pub peak_latency_ms: f64,
    pub sample_count: usize,
}

// ============================================================================
// 3. Swarm, Handoff & Encrypted Context Ledger DTOs
// ============================================================================

/// Journal entry recorded in `sub_agent_diaries` table.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SubAgentDiaryEntry {
    pub id: Option<i64>,
    pub agent_id: String,
    pub session_id: String,
    pub content: String,
    pub created_at: i64,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_agent_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub turn_index: Option<u32>,
}

/// Entry in the tamper-evident context ledger for swarm state handoff.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ContextLedgerEntry {
    pub ledger_id: String,
    pub session_id: String,
    pub sender_agent_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recipient_agent_id: Option<String>,
    pub payload_encrypted: Vec<u8>,
    pub nonce: Vec<u8>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
    pub checksum_sha256: String,
    pub timestamp_epoch_ms: i64,
}

/// Payload transferred during inter-agent turn transition (`handoff`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SwarmHandoffPayload {
    pub handoff_id: String,
    pub source_agent: String,
    pub target_agent: String,
    pub task_description: String,
    pub context_summary: String,
    pub variables: serde_json::Value,
    pub created_at: i64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_e3_score_calculation() {
        let score = E3EfficiencyScore::new(1.0, 1.0, 1.0);
        assert!((score.composite_score - 1.0).abs() < 1e-6);

        let partial = E3EfficiencyScore::new(0.5, 0.8, 0.9);
        // composite = 0.9*0.40 + 0.8*0.35 + 0.5*0.25 = 0.36 + 0.28 + 0.125 = 0.765
        assert!((partial.composite_score - 0.765).abs() < 1e-6);
    }

    #[test]
    fn test_hardware_constants_sanity() {
        assert!(RTX_2060M_WDDM_CEILING_MB < RTX_2060M_VRAM_TOTAL_MB);
        assert_eq!(RTX_2060M_VRAM_TOTAL_MB, 6144);
        assert_eq!(MIN_PCIE_BANDWIDTH_GBPS_FOR_SPILLOVER, 32.0);
    }
}
